### PR TITLE
Add a CloudFormation template

### PR DESCRIPTION
**Pull request by chris-redekop**
Thanks for a great lab.  I wrote a CloudFormation template as I followed the instructions.  Would you like to include it with the README and the Python script?

### CODE REVIEW

**Comment by diegonat** [comment]
Chris, can your pull have a separate lambda python script? In this way, I do not need to change lambda_backup.py for a few reasons.

**Comment by chris-redekop** [comment]
Sure, I can remove the python script.

This will create an issue, though, where the `master` version of the python script won't find the SSM Document when it looks for it as `ASGLogBackup`.  (I don't see a way to provide `ASGLogBackup` or any name to the [AWS::SSM::Document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-document.html) resource in CFn.)

(How) do you want to address this before merging this branch?

**Comment by diegonat** [comment]
I would like to have two different scripts one for the cloudformation template and the other as it is now. The one for CF would be the one you provided that gets the name from the ENV.

**Comment by chris-redekop** [comment]
I moved the CFn files to their own CFn directory, leaving the original `lambda_backup.yaml` file as-is.

**Comment by diegonat** [comment]
Thank you a lot! Great work!

**Pull request merged**
